name: Remove blocked renovate Pull Requests

on:
  # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
  # as per above: Scheduled workflows will only run on the default branch.
  # schedule:
  #   - cron:  "*/5 * * * *"
  # to enable manual triggering of the workflow via Github -> Actions
  workflow_dispatch:

env:
  GITHUB_REPOS: 'red-hat-data-services/rhods-operator red-hat-data-services/RHOAI-Build-Config'

permissions:
  contents: write
  pull-requests: write
  checks: write
  security-events: write
  statuses: write

jobs:
  remove-blocked-prs:
    runs-on: ubuntu-latest
    steps:
      - name: find and report (Slack) OPEN or CLOSED blocked renovate Pull Requests
        id: find-blocked-renovate-pull-requests
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SLACK_WORKFLOW_URL: ${{ secrets.SLACK_WORKFLOW_URL }}
        run: |
          #!/usr/bin/env bash

          send_error_report_to_slack(){
            echo "script failed, sending error report over Slack"
            curl -X POST \
              -H 'Content-type: application/json' \
              -d '{"msg_pre": "GitHub Workflow *'"${2}"'* exited with code '"${1}"'. '"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"'"}' \
              $SLACK_WORKFLOW_URL
          }

          trap 'EXITCODE=$?; SCRIPT_NAME=$0; if [ $EXITCODE -ne 0 ]; then send_error_report_to_slack $EXITCODE "$GITHUB_WORKFLOW"; fi; exit $EXITCODE' 1 2 3 6 14 15 EXIT
          set -ue # fail on any error or unset variable

          echo "GITHUB_REPOS: ${GITHUB_REPOS[@]}"

          for REPO_NAME in ${GITHUB_REPOS}; do
            echo -e "\n\n- PROCESSING REPO: $REPO_NAME"

            RUN_DATETIME=$(date +%Y-%m-%d_%H:%M:%S)

            IFS="\n"
            echo "-- PROCESSING OPEN PULL REQUESTS FOR $REPO_NAME"
            PRS_RAW=$(gh search prs  \
                        --state=open \
                        --label=konflux-nudge \
                        --repo="${REPO_NAME}" \
                        --match comments "because it does not recognize the last commit author" \
                        --json "number,title,state,url" \
                        | jq -r '.[] | [.number, .title, .state, .url] | @csv')

            echo "-- PROCESSING CLOSED PULL REQUESTS FOR $REPO_NAME"
            PRS_RAW+=$(gh search prs  \
                        --state=closed \
                        --label=konflux-nudge \
                        --repo="${REPO_NAME}" \
                        --match comments "because it does not recognize the last commit author" \
                        --json "number,title,state,url" \
                        | jq -r '.[] | [.number, .title, .state, .url] | @csv' \
                        | head -1 )

            echo -e "\n--- PRS_RAW --- \n$PRS_RAW \n/--- PRS_RAW ---"

            if [ "$PRS_RAW" != "" ] ; then
              while read -r line; do
                echo "processing line/ $line /line"
                IFS="," read -r -a PR <<<"$line"

                set -x
                curl -X POST \
                  -H 'Content-type: application/json' \
                  -d '{"msg_pre": "-->", "run_datetime": "'$RUN_DATETIME'", "repo_name": "'"${REPO_NAME}"'", "pr_number":"'${PR[0]}'", "pr_title": '${PR[1]}', "pr_state": '${PR[2]}', "pr_url": '"${PR[3]}"', "msg_post": ""}' \
                  $SLACK_WORKFLOW_URL
                set +x

                # sleep to not to hit Slack ratelimiting (e.g.: when you try to send more than 10 msgs within 1 sec window)
                sleep 0.5
              done <<<$PRS_RAW
            fi

          done
